<?php

$texts = [
    'project.link'                                          => 'Project on GitHub',
    'project.log_in'                                        => 'Let me in',

    'error.not.installed.title'                             => '未インストール',
    'error.not.installed.description'                       => 'OpCacheがインストールされていないようです',
    'error.not.enabled.title'                               => '有効になっていません',
    'error.not.enabled.description'                         => 'OpCacheが有効になっていないようです',

    'menu.status'                                           => 'ステータス',
    'menu.config'                                           => '設定',
    'menu.scripts'                                          => 'キャッシュされたスクリプト',
    'menu.graphs'                                           => 'グラフ',

    'reset.submit'                                          => 'リセット',
    'confirmation.reset'                                    => '本当にキャッシュをリセットしますか?',
    'confirmation.yes'                                      => 'はい',
    'confirmation.no'                                       => 'いいえ',

    'status.title'                                          => 'ステータス',
    'status.opcache_enabled'                                => '有効',
    'status.cache_full'                                     => 'キャッシュがいっぱいです',
    'status.restart_pending'                                => '再起動の保留中',
    'status.restart_in_progress'                            => '再起動中',

    'memory.title'                                          => 'メモリ使用量',
    'memory.used_memory'                                    => '使用中のメモリ',
    'memory.free_memory'                                    => '空きメモリ',
    'memory.wasted_memory'                                  => '廃棄されたメモリ',
    'memory.current_wasted_percentage'                      => 'Currently wasted',

    'stats.title'                                           => '統計',
    'stats.num_cached_scripts'                              => 'キャッシュされたスクリプト',
    'stats.num_cached_keys'                                 => 'キャッシュされたキー'',
    'stats.max_cached_keys'                                 => '最大キャッシュキー',
    'stats.hits'                                            => 'Hits',
    'stats.start_time'                                      => '起動時間',
    'stats.last_restart_time'                               => '前回の再起動',
    'stats.oom_restarts'                                    => 'Oom の再起動',
    'stats.hash_restarts'                                   => 'ハッシュ再開',
    'stats.manual_restarts'                                 => '手動再起動',
    'stats.misses'                                          => 'Misses',
    'stats.blacklist_misses'                                => 'Blacklist misses',
    'stats.blacklist_miss_ratio'                            => 'Miss率',
    'stats.opcache_hit_rate'                                => 'Opcache hit率',

    'config.title'                                          => '設定',
    'config.opcache.enable'                                 => '有効',
    'config.opcache.enable.description'                     => 'Zend OPCacheが有効になっているかどうかを確認します。',
    'config.opcache.enable_cli'                             => '有効 (CLI)',
    'config.opcache.enable_cli.description'                 => 'CLIバージョンのPHPでZend OPCacheが有効になっているかどうかを確認します。',
    'config.opcache.use_cwd'                                => '現在の作業ディレクトリに基づくキー',
    'config.opcache.use_cwd.description'                    => 'このディレクティブが有効になっていると、OPcacheは現在の作業ディレクトリをスクリプトキーに追加し、同じ名前（basename）のファイル間で起こりうる衝突を排除します。このディレクティブを無効にすると、パフォーマンスは向上しますが、既存のアプリケーションが破損する可能性があります。',
    'config.opcache.validate_timestamps'                    => 'タイムスタンプの検証',
    'config.opcache.validate_timestamps.description'        => '無効にすると、OPcacheを手動でリセットするか、Webサーバーを再起動してファイルシステムの変更を有効にする必要があります。',
    'config.opcache.inherited_hack'                         => '継承されたハック',
    'config.opcache.inherited_hack.description'             => '',
    'config.opcache.dups_fix'                               => 'Dups fix',
    'config.opcache.dups_fix.description'                   => '',
    'config.opcache.revalidate_path'                        => ''パスの再検証',
    'config.opcache.revalidate_path.description'            => 'include_path最適化でファイル検索を有効または無効にします。'',
    'config.opcache.log_verbosity_level'                    => 'ログ詳細レベル',
    'config.opcache.log_verbosity_level.description'        => 'すべてのOPcacheエラーはWebサーバーのログに記録されます。デフォルトでは、致命的なエラー（レベル0）またはエラー（レベル1）のみが記録されます。警告（レベル2）、情報メッセージ（レベル3）、またはデバッグメッセージ（レベル4）を有効にすることもできます。',
    'config.opcache.memory_consumption'                     => 'Opcache メモリサイズ',
    'config.opcache.memory_consumption.description'         => 'OPcache共有メモリの記憶容量です。',
    'config.opcache.interned_strings_buffer'                => 'Interned strings buffer',
    'config.opcache.interned_strings_buffer.description'    => 'サポートされている文字列のメモリ量（MB単位）',
    'config.opcache.max_accelerated_files'                  => '最大キャッシュスクリプト',
    'config.opcache.max_accelerated_files.description'      => 'OPcacheハッシュテーブルのキー（スクリプト）の最大数。 200～100000の範囲で設定して下さい。',
    'config.opcache.max_wasted_percentage'                  => 'Maximum wasted before restart',
    'config.opcache.max_wasted_percentage.description'      => '再起動がスケジュールされるまでの無駄なメモリの最大の割合',
    'config.opcache.consistency_checks'                     => '整合性チェック頻度',
    'config.opcache.consistency_checks.description'         => 'N回のリクエストごとにキャッシュのチェックサムをチェックします。デフォルト値の "0"はチェックが無効であることを意味します。',
    'config.opcache.force_restart_timeout'                  => '強制再起動タイムアウト',
    'config.opcache.force_restart_timeout.description'      => 'キャッシュがアクセスされていない場合にスケジュールされた再起動を開始するまでの待機時間（秒）',
    'config.opcache.revalidate_freq'                        => '変更を確認する頻度',
    'config.opcache.revalidate_freq.description'            => 'ファイルのタイムスタンプをチェックして共有メモリーの記憶域割り当てを変更する頻度（秒単位）。 "1"は、1秒に1回検証することを意味しますが、要求ごとに1回のみ検証します。 "0"は常に検証することを意味します。',
    'config.opcache.preferred_memory_model'                 => '',
    'config.opcache.preferred_memory_model.description'     => '優先共有メモリバックエンド。空のままにして、システムに決定させて下さい。',
    'config.opcache.blacklist_filename'                     => 'ブラックリスト',
    'config.opcache.blacklist_filename.description'         => 'OPcacheブラックリストファイルの場所です（ワイルドカードが許可されています）。各OPcacheブラックリストファイルは、加速すべきではないファイルの名前を保持するテキストファイルです。ファイル形式は、各ファイル名を新しい行に追加することです。ファイル名はフルパスでも、ファイルプレフィックスでもかまいません（つまり、 /var/www/x は /var/www の \'x\' で始まるすべてのファイルとディレクトリをブラックリストします）。 aで始まる行。無視されます（コメント）。',
    'config.opcache.max_file_size'                          => 'サイズを超えたキャッシュを除外',
    'config.opcache.max_file_size.description'              => '大きなファイルをキャッシュから除外できるようにします。デフォルトでは、すべてのファイルがキャッシュされます。',
    'config.opcache.error_log'                              => 'エラーログ',
    'config.opcache.error_log.description'                  => 'OPcacheエラーログファイル名。空の文字列は "stderr"とみなされます。',
    'config.opcache.protect_memory'                         => 'メモリを保護する',
    'config.opcache.protect_memory.description'             => 'スクリプトの実行中に共有メモリが予期しない書き込みから保護されます。内部デバッグにのみ有効です。',
    'config.opcache.save_comments'                          => 'コメントを保存',
    'config.opcache.save_comments.description'              => '無効にすると、すべてのPHPDocコメントがコードから削除され、最適化されたコードのサイズが小さくなります。',
    'config.opcache.load_comments'                          => 'コメントを読み込む',
    'config.opcache.load_comments.description'              => '無効にすると、PHPDocコメントはSHMから読み込まれないので、「Docコメント」は常に保存されますが（save_comments = 1）、アプリケーションを必要としないアプリケーションとにかく。',
    'config.opcache.fast_shutdown'                          => '高速シャットダウン',
    'config.opcache.fast_shutdown.description'              => '有効にすると、高速化されたコードに対して高速シャットダウンシーケンスが使用されます。',
    'config.opcache.enable_file_override'                   => 'ファイルオーバーライド',
    'config.opcache.enable_file_override.description'       => 'ファイル存在のオーバーライドを許可する（file_existsなど）パフォーマンス機能。',
    'config.opcache.optimization_level'                     => '最適化レベル',
    'config.opcache.optimization_level.description'         => '各ビットが適切なOPcacheパスを有効または無効にするビットマスク。',

    'blacklist.title'                                       => 'ブラックリスト',
    'blacklist.empty'                                       => 'ブラックリストに載っているスクリプトはありません',

    'scripts.title'                                         => 'キャッシュされたスクリプト',
    'scripts.overview.title'                                => '概要',
    'scripts.empty'                                         => 'スクリプトはキャッシュされません',
    'scripts.directory.script_count'                        => ' (<i class="count">%s</i> ファイル)',
    'scripts.full_path'                                     => 'ファイル名',
    'scripts.hits'                                          => 'Hits',
    'scripts.memory_consumption'                            => 'グラフ',
    'scripts.last_used_timestamp'                           => '最後に使用',
    'scripts.timestamp'                                     => '作成',
    'scripts.actions'                                       => '作成済み',
    'script.invalidate'                                     => '無効化',
    'scripts.filter.placeholder'                            => 'キャッシュされたスクリプトをフィルタする',

    'graph.title'                                           => 'グラフ',
    'graph.memory.title'                                    => 'グラフ',
    'graph.memory.free'                                     => '空き',
    'graph.memory.used'                                     => '使用済み',
    'graph.memory.wasted'                                   => '廃棄済み',
    'graph.keys.title'                                      => 'キー',
    'graph.keys.free'                                       => '空き',
    'graph.keys.scripts'                                    => '使用済み',
    'graph.keys.wasted'                                     => '廃棄済み',
    'graph.hits.title'                                      => 'Hits',
    'graph.hits.hits'                                       => 'hits',
    'graph.hits.misses'                                     => 'misses',
    'graph.hits.blacklist'                                  => 'ブラックリスト'
];
